#lang datalog
is_even(0,true).
is_even(1,false).
is_even(X,Y):- X != 0,X != 1, X1:- -(X,2),is_even(X1,Y).
is_even(100,X)?
is_even(101,X)?

integer_sum(1,1).
integer_sum(X,Y):- X != 1, X1:- -(X,1),
  integer_sum(X1,R1), Y:-+(X,R1).

integer_sum(10,X)?
integer_sum(100,X)?

square_sum(1,1).
square_sum(X,Y):- X != 1, X1:- -(X,1), X2:- *(X,X),
  square_sum(X1, Y1), Y:- +(Y1,X2).
square_sum(10,X)?
square_sum(100,X)?

f1(X,Y):- P:- >(X,0), P = true,
  Y1:- log(X), Y2:- *(Y1,Y1), Y:- /(1,Y2).

f1(10, X)?
f1(-10, X)?

fibo(0,0).
fibo(1,1).

fibo(N,F):- N != 0, N != 1, N1:- -(N,1), N2:- -(N,2),
  fibo(N1, F1), fibo(N2, F2), F:- +(F1,F2).

fibo(30,F)?
